services:
  nginx:
    container_name: nginx-service
    image: nginx:latest
    volumes:
      - ../nginx/logs:/var/log/nginx
      - ../nginx/templates:/etc/nginx/templates
      - ../nginx/res:/usr/share/nginx/html
    ports:
      - "${NGINX_OUTER_PORT}:${NGINX_INNER_PORT}"
    environment:
      NGINX_INNER_PORT: ${NGINX_INNER_PORT}
      
      CORE_PORT: ${CORE_PORT}
      
      AUTH_PORT: ${AUTH_PORT}
      
      KNOWLEDGEBASE_PORT: ${KNOWLEDGEBASE_PORT}
    networks:
      - network-bridge
