services:
  core:
    container_name: core-service
    build: 
      context: ../core
      args:
        CORE_PORT: ${CORE_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      
      AUTH_HOST: ${AUTH_HOST}
      AUTH_PORT: ${AUTH_PORT}

      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

      MINIO_API_HOST: ${MINIO_API_HOST}
      MINIO_API_PORT: ${MINIO_API_PORT}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

      LOG_LEVEL: ${LOG_LEVEL}
      CREATE_DATABASE: ${CREATE_DATABASE}

      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "${CORE_PORT}:${CORE_PORT}"
    restart: unless-stopped
    networks:
      - network-bridge
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${CORE_PORT}/config" ]
      interval: 2s
      timeout: 10s
      retries: 5
