services:
  knowledgebase:
    container_name: knowledgebase-service
    build: 
      context: ../knowledgebase
      args:
        KNOWLEDGEBASE_PORT: ${KNOWLEDGEBASE_PORT}

        LOG_LEVEL: ${LOG_LEVEL}
    ports:
      - "${KNOWLEDGEBASE_PORT}:${KNOWLEDGEBASE_PORT}"
    restart: unless-stopped
    environment:
      AUTH_HOST: ${AUTH_HOST}
      AUTH_PORT: ${AUTH_PORT}

      CORE_HOST: ${CORE_HOST}
      CORE_PORT: ${CORE_PORT}

      SECRET_KEY: ${SECRET_KEY}
    networks:
      - network-bridge
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${KNOWLEDGEBASE_PORT}/test" ]
      interval: 2s
      timeout: 10s
      retries: 5
