services:
  redis:
    container_name: "redis-service"
    image: "redis:latest"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_USER: ${REDIS_USER}
      REDIS_USER_PASSWORD: ${REDIS_USER_PASSWORD}
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - network-bridge